feat(Drawer): add Drawer component
narmi/design_system pull request #861
Opened 2022-12-20 15:17 UTC by rogerioshieh

Drawer component that opens up via an animation:

https://user-images.githubusercontent.com/40327446/208700326-e3ca2e55-20b2-4632-89f4-b263c5db21ab.mov

Component's API:
<img width="939" alt="image" src="https://user-images.githubusercontent.com/40327446/208700437-2c1a89bd-95e5-468d-8e0f-17d024a2db73.png">

2022-12-20 19:05 UTC, akdetrick requested changes
Looking good!
Left a couple of comments for minor changes

2022-12-20 19:05 UTC, akdetrick commented on src/Drawer/index.js
> +        `drawer navigation ${position}`,
This is definitely the right approach to composing the classes here - for the sake of consistency, I'd like to change some of the class names to match our [naming conventions](https://github.com/narmi/design_system/blob/main/contributing/naming-conventions.md#css)

For example:
```diff
-.drawer.bottom
+.drawer--bottom
```

```diff
-.drawer.in
+.drawer--transitioning
```

This convention helps the component stay consistent with the naming in the rest of the project and also flattens the CSS specificity of each variant state to `10`

2022-12-20 19:08 UTC, akdetrick commented on src/Drawer/index.js
> +  const prevOrNext = (opposite = false) => {
On closer inspection, it looks like we already use CSS to change the order of buttons.
Do we actually need `prevOrNext`, or should the callbacks be invoked directly?

2022-12-21 15:22 UTC, rogerioshieh commented on src/Drawer/index.js
> +  const prevOrNext = (opposite = false) => {
I am not exactly sure why I had done it that way at first, but you're totally right--I simplified the logic now to call them directly

2022-12-21 21:03 UTC, akdetrick approved these changes
🚢

2022-12-21 21:06 UTC, merged